### ISSUE TITLE
The program closes when a big number of downloads is reached

### ISSUE THREAD

**Issue by xiveslestian** [FatherFoxxy/JustE621DL#1]
First of all - very nice programm, easy to use and pleasant to the eye!
I am using it do download a lot of files - 20k+
for example: "rating:explicit score:>=50 type:jpg" - 22k files

when a certain number of downloads is completed(sometimes 7k, sometimes more), the program crashes without any messages.
Also the naming of downloads could use some tweaking, just a simple md5.ext name would be best, post_number_md5.ext would be a great addition!
Instead of using "#" for symbols in folder names, a "_" would be better in my opinion.

**Comment by FatherFoxxy** [comment]
Fixed in https://github.com/FatherFoxxy/JustE621DL/commit/7ec7565e9e3fd744e67b1f7242a17bcf94b977a7
