### ISSUE TITLE
Unhandled Exception loop when downloading

### ISSUE THREAD

**Issue by RadiantSpark** [FatherFoxxy/JustE621DL#2]
Trying to download will very often come up with this error.

Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Value of '-39425' is not valid for 'Maximum'. 'Maximum' must be greater than or equal to 0.
Parameter name: Maximum.

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '-39425' is not valid for 'Maximum'. 'Maximum' must be greater than or equal to 0.
Parameter name: Maximum
   at System.Windows.Forms.ProgressBar.set_Maximum(Int32 value)
   at JustE621DL.DownloadController.SetProgressBarMaximum(Int32 maximum)
   at JustE621DL.DownloadController.CheckPostCountTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
JustE621DL
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/E621SharpDL/JustE621DL.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2094.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2093.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`

**Comment by FatherFoxxy** [comment]
Please provide additional information. What tags were you trying to download, for example?

**Comment by RadiantSpark** [comment]
My tag list only had 'blitzdrachin' and my blacklist had the following tags separated by line: female, scat, watersports, tits, vagina, intersex, dickgirl. I was downloading in the 'raw' quality. 
Do note that I tried a number of different tags and at most it would get to about 10 images downloaded before giving this error, albeit with different numbers each time.
I'm not sure what other information I can give that would be helpful.

**Comment by FatherFoxxy** [comment]
Could you screenshot the entire program before pressing the download button please?

**Comment by RadiantSpark** [comment]
This is before clicking 'Start'
https://puu.sh/wQlFY/50ad33414d.png

This is after, with the error popping up
https://puu.sh/wQlH6/ed974064c9.png

**Comment by FatherFoxxy** [comment]
I have fixed the issue and will be issuing a release shortly.

**Comment by FatherFoxxy** [comment]
Fixed in https://github.com/FatherFoxxy/JustE621DL/commit/32ce1c8ee084d19478b35e68737f23ede9c406f5
